name: 'Post Merge CI'

on:
  push:
    branches:
      - main

jobs:
  validate:
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install
        run: npm ci

      # - name: Unit test
      #   run: npm run test:cov

  release:
    if: github.event_name == 'push' && !startsWith(github.event.head_commit.message, 'chore(release):')
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Release npm package
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
