name: 'Pull Request CI'

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Install
        run: npm ci

      - name: Format and lint
        run: npm run lint && npm run format:check

      # - name: Unit test
      #   run: npm run test:cov
